[run]
init_cmds = [                      # Commands run in start
  ["bash", "-c", "GOARCH=wasm GOOS=js go build -o main.wasm ./app/main.go"],
  ["go", "run", "server.go"]
]
watch_all = true                   # Watch all sub-directories
watch_dirs = ["./app"]                    # Directories to watch
watch_exts = [".go"]               # Extensions to watch
ignore = [".git", "node_modules"]  # Directories to exclude from watching
ignore_files = []                  # Regexps for ignoring specific notifies
follow_symlinks = false            # Enable/disable following symbolic links of sub directories
build_delay = 1500                 # Minimal interval to Trigger build event
interrupt_timout = 15              # Time to wait until force kill
graceful_kill = false              # Wait for exit and before directly kill
cmds = [                           # Commands to run
  ["bash", "-c", "lsof -n -i:8080 | grep LISTEN | awk '{ print $2 }' | uniq | xargs kill -9"],
  ["bash", "-c", "GOARCH=wasm GOOS=js go build -o main.wasm ./app/main.go"], # || GOARCH=wasm GOOS=js go build -ldflags \"-X main.MODE=err\" -o main.wasm ./err-page/main.go
  ["go", "run", "server.go"]
]

